name: Test CloudBlue Connect Standard Transformations

on:
  push:
    branches: '*'
    tags:
        - '*'
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false --local
          poetry install --no-root
      - name: Linting
        run: |
          flake8 .
      - name: Testing
        run: |
          pytest
